apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cluster-api-provider-kubevirt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cluster-api-provider-kubevirt
    app.kubernetes.io/part-of: mce-25
  name: cluster-api-provider-kubewkbg
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cluster-api-provider-kubevirt
    weight: 100
status: {}
